### ISSUE TITLE
Refactor API for configuring item checkmark

### ISSUE THREAD

**Issue by web-padawan** [vaadin/vaadin-list-box#67]
1) in `vaadin-item` we have this [code](https://github.com/vaadin/vaadin-item/blob/4d361148606871f43a42c46343ed5529cb78d78e/theme/lumo/vaadin-item-styles.html#L26):

```css
:host([tabindex])::before {
  display: var(--_lumo-item-selected-icon-display, none);
  content: var(--lumo-icons-checkmark);
}
```

2) In `vaadin-list-box` we use it [like this](https://github.com/vaadin/vaadin-list-box/blob/3e3765cdb91576931a4fcd3a56472d9c7e77cba5/theme/lumo/vaadin-list-box-styles.html#L10)

```css
:host {
  --_lumo-item-selected-icon-display: var(--_lumo-list-box-item-selected-icon-display, block);
}
```

3) In `vaadin-context-menu`, we override it [like this](https://github.com/vaadin/vaadin-context-menu/blob/080e93077f3e92d4f2fa2ac7032bd2bd1f565579/theme/lumo/vaadin-context-menu-styles.html#L25):

```css
:host {
  --_lumo-list-box-item-selected-icon-display: none;
}
```

4) However, in context-menu with nested menus, we reset it [like this](https://github.com/vaadin/vaadin-context-menu/blob/080e93077f3e92d4f2fa2ac7032bd2bd1f565579/theme/lumo/vaadin-context-menu-styles.html#L40):

```css
:host(.vaadin-menu-list-box) {
  --_lumo-list-box-item-selected-icon-display: block;
}
```

In future major releases, we need to come up with a better API.
